### PR TITLE
Fix merging problems 

### PR DESCRIPTION
**Pull request by linuxscout**
- Fix  grammar rules
- fix disambiguation
- update my repository with yours updates

### CODE REVIEW

**Comment by sohaibafifi** [comment]
Do you use the css and schemas files ?

**Comment by sohaibafifi** [comment]
The commit messages should start with [ar]

**Comment by linuxscout** [comment]
They recommand  to use css file with xxe editor as described in [http://wiki.languagetool.org/tips-and-tricks](http://wiki.languagetool.org/tips-and-tricks)

> Using xxe for editing rules

> It's possible to edit rules using XML Mind XML Editor (xxe) in a WYSYWIM (what you see is what you mean) mode. The program is available in a free version for many platforms (as it's developed in Java) though it's not open source. It offers spell-checking and validation, and we have developed special CSS files to make editing files easier. Put these in the rules directory.

**Comment by sohaibafifi** [comment]
This files are already present in the parent and correctly linked in the head

**Pull request closed without merging**
